const topicToCategory = {
  "Action-adventure_game": "games",
  Action_game: "games",
  American_football: "sports",
  Association_football: "sports",
  Basketball: "sports",
  Christian_music: "music",
  Cricket: "sports",
  Electronic_music: "music",
  Entertainment: "entertainment",
  Fashion: "lifestyle",
  Film: "lifestyle",
  Food: "lifestyle",
  Health: "lifestyle",
  Hip_hop_music: "music",
  Hobby: "lifestyle",
  Humour: "comedy",
  Independent_music: "music",
  Knowledge: "education",
  "Lifestyle_(sociology)": "lifestyle",
  Music: "music",
  Music_of_Asia: "music",
  Music_of_Latin_America: "music",
  Performing_arts: "arts",
  Pet: "animals",
  Physical_fitness: "sports",
  Politics: "news",
  Pop_music: "music",
  Professional_wrestling: "sports",
  Religion: "religion",
  Rock_music: "music",
  "Role-playing_video_game": "games",
  Simulation_video_game: "games",
  Society: "society",
  Sport: "sports",
  sports_game: "games",
  Strategy_video_game: "games",
  Technology: "tech",
  Television_program: "entertainment",
  Tourism: "travel",
  Vehicle: "automobiles",
  Video_game_culture: "games",
};
const categoryMap = {
  "film & animation": "1",
  "autos & vehicles": "2",
  music: "10",
  animals: "15",
  sports: "17",
  travel: "22",
  games: "20",
  "people & blogs": "19",
  comedy: "23",
  entertainment: "24",
  news: "25",
  "howto & style": "27",
  education: "26",
  tech: "28",
  "nonprofits & activism": "29",
  movies: "30",
  "anime/animation": "31",
  "action/adventure": "32",
  classics: "33",
  documentary: "35",
  drama: "36",
  family: "37",
  foreign: "38",
  horror: "39",
  "sci-fi/fantasy": "40",
  thriller: "41",
  shorts: "42",
  shows: "43",
  trailers: "44",
};

module.exports = { topicToCategory, categoryMap };
